[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    openenergymonitor/EmonLib
    blynkkk/Blynk
    knolleary/PubSubClient
    emelianov/modbus-esp8266
build_flags =
    -D IEEC_ENABLE_BLYNK=1
    -D IEEC_ENABLE_MQTT=1
    -D IEEC_ENABLE_MODBUS=1

[env:native]
platform = native
test_framework = unity
test_filter = test_native
build_flags = -D UNIT_TEST
build_src_filter = +<energy_logic.cpp>
